/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AGame.java
 *
 * Created on Feb 14, 2012, 10:25:35 AM
 */
package BlackJack;

import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Jordan
 */
public class AGame extends JFrame {

    /** Creates new form AGame */
    private ArrayList<String> aids, notAids;
    public AGame() 
    {
        aids = new ArrayList<>();
        notAids = new ArrayList<>();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        whoHasAids = new javax.swing.JLabel();
        Ok = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        whoHasAids.setText("Who has aids? ");

        Ok.setText("OK");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        Clear.setText("Clear");

        display.setColumns(20);
        display.setRows(5);
        scroll.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(whoHasAids)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Clear))
                            .addComponent(textField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whoHasAids))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        display.append(tellIfAids(textField.getText()) + "\n");
    }//GEN-LAST:event_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AGame().setVisible(true);
            }
        });
    }
    
    private String tellIfAids(String n)
    {
        if(notAids.contains(n))
        {
            return n + " doesn't have aids";
        }
        else if(aids.contains(n))
        {
            return n + " 100% has aids";
        }
        else
        {
            return "Not in database ("+n+")";
        }
    }
    private void setUpAids()
    {
        aids.add("Nolan");
        aids.add("Spencer");
        aids.add("Tim Choh");
        notAids.add("Jordan");
        notAids.add("Barry");
        notAids.add("Martin");
        notAids.add("Heichman");
        notAids.add("Sam");
        notAids.add("Alan");
        notAids.add("Nooch");
        notAids.add("Heil Kyle");
        notAids.add("Mein Fuhrer");
        notAids.add("Kyle");
        notAids.add("Bonucci");
        notAids.add("Mom");
        notAids.add("Dad");
        notAids.add("Boo");
        notAids.add("Huskus");
        notAids.add("Claudia");
        notAids.add("Mike");
        notAids.add("Debbi");
        notAids.add("Boo");
        notAids.add("G");
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Ok;
    private javax.swing.JTextArea display;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField textField;
    private javax.swing.JLabel whoHasAids;
    // End of variables declaration//GEN-END:variables
}
